version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - plantuml
    - protobuf-compiler


python:
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: true
