# SPDX-License-Identifier: BSD-3-Clause
# Copyright(C) 2024 Intel Corporation
# Authors:
#   Kumar Amber
#   Hector Blanco Alcaine


---
- name: Copy files to target end-station nodes
  hosts: listener_nodes talker_nodes
  gather_facts: false
  tasks:

    - name: Create local directory
      ansible.builtin.file:
        path: "{{ dest }}/"
        state: directory

    - name: Transfer detd.deb package
      copy:
        src: files/detd_0.1.dev0-1_all.deb
        dest: "{{ dest }}/detd_0.1.dev0-1_all.deb"
        mode: u+rw

    - name: Transfer detd_apps.py
      copy:
        src: files/detd_apps.py
        dest: "{{ dest }}/detd_apps.py"
        mode: u+rwx

    - name: Transfer execute_detd.sh
      copy:
        src: files/execute_detd.sh
        dest: "{{ dest }}/execute_detd.sh"
        mode: u+rwx
