---
- name: Deploy talker
  hosts: server_talker
  become: yes
  tasks:
    - name: Transfer detd_talker to talker server
      copy:
        src: files/detd_talker.py
        dest: "{{ talker_dest }}/detd_talker.py"
        mode: '0755'

    - name: Transfer execute_talker_txrx to talker server
      copy:
        src: files/execute_talker_txrx.sh
        dest: "{{ talker_dest }}/execute_talker_txrx.sh"
        mode: '0755'

    - name: Transfer detd.deb package to talker server
      copy:
        src: files/detd_0.1.dev0-1_all.deb
        dest: "{{ talker_dest }}/detd_0.1.dev0-1_all.deb"

    - name: Transfer txrx to talker server
      copy:
        src: files/txrx
        dest: "{{ talker_dest }}/txrx"
        mode: '0755'

    - name: Run execute_talker_txrx asynchronously
      command: "{{ talker_dest }}/execute_talker_txrx.sh"
      args:
        chdir: "{{ talker_dest }}"
      become: yes
      async: 600
      poll: 0
      register: talker_async

    - name: Print script output
      debug:
        var: talker_result
      when: talker_result.stdout is defined

- name: Deploy Listener
  hosts: server_listener
  become: yes
  tasks:
    - name: Transfer detd_listener to listener server
      copy:
        src: files/detd_listener.py
        dest: "{{ listener_dest }}/detd_listener.py"
        mode: '0755'

    - name: Transfer execute_listener_txrx to listener server
      copy:
        src: files/execute_listener_txrx.sh
        dest: "{{ listener_dest }}/execute_listener_txrx.sh"
        mode: '0755'

    - name: Transfer detd.deb package to listener server
      copy:
        src: files/detd_0.1.dev0-1_all.deb
        dest: "{{ listener_dest }}/detd_0.1.dev0-1_all.deb"

    - name: Transfer txrx to listener server
      copy:
        src: files/txrx
        dest: "{{ listener_dest }}/txrx"
        mode: '0755'

    - name: Run execute_listener_txrx asynchronously
      command: "{{ listener_dest }}/execute_listener_txrx.sh"
      args:
        chdir: "{{ listener_dest }}"
      become: yes
      async: 600
      poll: 0
      register: listener_async

    - name: Wait for execute_listener_txrx to finish
      async_status:
        jid: "{{ listener_async.ansible_job_id }}"
      register: listener_result
      until: listener_result.finished
      retries: 30
      delay: 10

    - name: Transfer logs from listener server to control node
      fetch:
        src: "{{ listener_dest }}/list_out.txt"
        dest: "{{ fetch_dest }}"
        flat: yes
      when: listener_result.finished

- name: Fetch logs from Talker
  hosts: server_talker
  become: yes
  tasks:
    - name: Transfer logs from talker server to control node
      fetch:
        src: "{{ talker_dest }}/talk_out.txt"
        dest: "{{ fetch_dest }}"
        flat: yes
