#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright(C) 2020-2022 Intel Corporation
# Authors:
#   Hector Blanco Alcaine

from detd import Service




if __name__ == '__main__':

    with Service() as srv:
        srv.run()
